// <auto-generated />
using Grpc_Demo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grpc.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Grpc_Demo.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 11,
                            FirstName = "Ann",
                            LastName = "Fox",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 22,
                            FirstName = "Sam",
                            LastName = "Doe",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 33,
                            FirstName = "Sue",
                            LastName = "Cox",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 44,
                            FirstName = "Tim",
                            LastName = "Lee",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 55,
                            FirstName = "Jan",
                            LastName = "Ray",
                            School = "Computing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
